### ISSUE TITLE
Add [MethodImpl(MethodImplOptions.AggressiveInlining)] to all methods of the structs in this package.

### ISSUE THREAD

**Issue by jmaine** [DotNetCross/NativeInts#2]
Add `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to all methods of the structs in this package.

**Comment by nietras** [comment]
@jmaine this is not needed. All methods are very very small and the JIT will inline them. No matter what one should use the new C# 9 `nint`/`nuint` feature instead. :)
